remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Note collective - La vie sociale des donn√©es]
description: [Antoine DEMAUDUIT Iban HOURCADE Lydie LOUNI Sandra LOUNI]
